language: ruby
rvm:
  - 1.9.2
  - 1.9.3

services:
  - mongodb

script:
  - rake spec
  - bundle exec cucumber

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 5 # give Web server some time to bind to sockets, etc
